name: Manual workflow

on:
  push:
  workflow_dispatch:

env: 
  TEST_REPOSITORY: org-workflow-test-organization 
jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: generate repository name
        id: repo-name
        run: |
          echo ::set-output name=name::$(openssl rand -hex 3)
      - name: create repository
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_TEST_TOKEN }}
          script: |
            github.repos.createInOrg({
              org: "${{ env.TEST_REPOSITORY }}",
              name: "${{ steps.repo-name.outputs.name }}",
            });
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '3s'
      - name: delete repository
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_TEST_TOKEN }}
          script: |
            github.repos.delete({
              owner: "${{ env.TEST_REPOSITORY }}",
              repo: "${{ steps.repo-name.outputs.name }}",
            });
