name: Manual workflow

on:
  push:
  workflow_dispatch:

env: 
  TEST_REPOSITORY: org-workflow-test-organization 
jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: generate repository name
        id: repo-name
        run: |
          echo ::set-output name=repo_name::$(echo openssl rand -hex 3)
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_TEST_TOKEN }}
          script: |
            github.repos.createInOrg({
              ${{ env.TEST_REPOSITORY }} ,
              ${{ steps.vars.repo-name.name }},
            });
