name: Manual workflow

on:
  push:
    branches: [main, e2e-test]
  workflow_dispatch:
  release:

env: 
  TEST_ORG: org-workflow-test-organization 
  APP_ID_STAGING: 93678
  APP_ID_PRODUCTION: 93006
  
jobs:
  test-github-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create repository
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_TEST_TOKEN }}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/e2e-test.js`)
            console.log(script(${{ env.APP_ID_STAGING }}, "${{ env.TEST_ORG }}", {github, core}))
