name: Manual workflow

on:
  push:
  workflow_dispatch:

env: 
  TEST_REPOSITORY: org-workflow-test-organization 
jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: generate random repository name and content
        id: random
        run: |
          echo ::set-output name=repo::$(openssl rand -hex 3)
          echo ::set-output name=content::$(dd if=/dev/urandom bs=1k count=1 2>/dev/null | base64)
      - name: create repository
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_TEST_TOKEN }}
          script: |
            github.repos.createInOrg({
              org: "${{ env.TEST_REPOSITORY }}",
              name: "${{ steps.random.outputs.repo }}",
            });
      - name: push random contents
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_TEST_TOKEN }}
          script: |
            github.repos.createOrUpdateFileContents({
              owner: "${{ env.TEST_REPOSITORY }}",
              repo: "${{ steps.repo-name.outputs.name }}",
              path: "test-file.md",
              message: "Test commit for https://github.com/SvanBoxel/organization-workflows",
              content: "${{ steps.random.outputs.content }}",
              commiter: {
                name: "github-actions[bot]",
                email: "github-actions[bot]@users.noreply.github.com"
              }
            });
      - name: Sleep for 100 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '100s'
      - name: delete repository
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_TEST_TOKEN }}
          script: |
            github.repos.delete({
              owner: "${{ env.TEST_REPOSITORY }}",
              repo: "${{ steps.repo-name.outputs.name }}",
            });
