name: E2E-test

on:
  push:
    branches: [main, e2e-test]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'production'

env: 
  TEST_ORG: org-workflow-test-organization 
  APP_ID_STAGING: 93678
  APP_ID_PRODUCTION: 93006
  
jobs:
  test-github-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create repository
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_TEST_TOKEN }}
          script: |
            const envMap = {
              production: ${{ env.APP_ID_PRODUCTION }},
              staging: ${{ env.APP_ID_STAGING }}
            }
            
            const APP_ID = envMap['${{ github.event.inputs.environment }}' || 'production']
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/e2e-test.js`)
            await script(APP_ID, "${{ env.TEST_ORG }}", {github, core})
            
